name: Rust

on: [push, pull_request]

jobs:
  build_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install alsa
        run: sudo apt update && sudo apt install libasound2-dev libgtk-3-dev
      - uses: Swatinem/rust-cache@v1
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release 
      - name: Chmod +x
        run: chmod +x target/release/neothesia
      - name: zip binary
        run: zip -rj app.zip target/release/neothesia
      - uses: actions/upload-artifact@v2
        with:
          name: ubuntu-artifact
          path: app.zip
  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release 
      - uses: actions/upload-artifact@v2
        with:
          name: windows-artifact
          path: target/release/neothesia.exe
  build_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release 
      - name: copy binary
        run: cp target/release/neothesia .github/app/Neothesia.app/Contents/MacOS
      - name: zip binary
        run: cd .github/app/ && zip -r app.zip Neothesia.app && cd ../..
      - uses: actions/upload-artifact@v2
        with:
          name: macos-artifact
          path: .github/app/app.zip
